#import "puppet-concat"
#
#class authorized_keys {
#  include concat::setup
#  $target = '/tmp/xx'
#
#  concat{$target:
#     owner => root,
#     group => root,
#     mode  => 644
#  }
#
#  concat::fragment{"header":
#     target  => $target,
#     content => "# This file is automatically generated by Puppet\n",
#     order   => 01,
#  }
#
#  concat::fragment{"a":
#     target  => $target,
#     source  => "puppet:///modules/authorized_keys/a",
#     order   => 14
#  }
#
#  concat::fragment{"b":
#     target  => $target,
#     source  => "puppet:///modules/authorized_keys/b",
#     order   => 15
#  }
#}

class roots {}